### ISSUE TITLE
ipysketch_lite doesn't let me draw anything

### ISSUE THREAD

**Issue by rogermeier** [MatthewAndreTaylor/ipysketch_lite#3]
I followed the instructions and installed ipysketch_lite with pip, and entered the following commands into Jupyter Notebook:

```
from ipysketch_lite import Sketch
sketch = Sketch()
```

The canvas to draw appears, but I doesn't let me draw with the mouse. clicking the mouse button doesn't draw anything. Is there anything I'm missing. I've tried this on macOS, Windows 11, and Ubuntu, all with the same result.

<img width="758" alt="Greenshot 2024-11-06 10 24 28" src="https://github.com/user-attachments/assets/fa5d845b-1e6b-4aec-891d-160a887b46b6">

**Comment by MatthewAndreTaylor** [comment]
I believe this is a regression as I progressed towards jupyter lite environments for the web.

If you install an earlier version for example `pip install ipysketch-lite==0.0.1` it should work for your case in a local environment

**Comment by rogermeier** [comment]
Thanks! That worked!

Sketch.image and Sketch.data don't seem to work though. Is there another way to retrieve the data?

Roger

**Comment by MatthewAndreTaylor** [comment]
In the previous versions api it is `Sketch.get_output()`  to get the base64 encoded image as a string and `Sketch.get_output_array()`

to get the sketch as a numpy array. (note numpy and pillow are needed for this functionality `pip install pillow`, `pip isntall numpy`)

**Comment by rogermeier** [comment]
Thanks! I was able to get it working!

```
# Save the sketch
output = sketch.get_output()
image_data = output.split(",")[1]
from PIL import Image
import io
import base64
image = Image.open(io.BytesIO(base64.b64decode(image_data)))
image.save("mysketch.png","PNG")

# Plot the sketch image or do image manipulation
import matplotlib.pyplot as plt
plt.imshow(image)
plt.show()
```

**Comment by MatthewAndreTaylor** [comment]
I have written a patch for this regression in [version 0.3.1](https://github.com/MatthewAndreTaylor/ipysketch_lite/releases/tag/0.3.1). Tested on both local environment without jupyter installed, as well as in a sample [jupyter lite environment](https://matthewandretaylor.github.io/ipysketch_lite/jupyterlite/lab/).

**Comment by rogermeier** [comment]
Perfect! Thanks. I can confirm that it works now.
